### ISSUE TITLE
Error: No default option is configured for constraint Symfony\Component\Validator\Constraints\File

### ISSUE THREAD

**Issue by jmontoyaa** [mediamonks/symfony-sonata-media-bundle#12]
When setting up the file/image constraints like this:

```
image_constraints:
        - minWidth: 100
        - minHeight: 100
        - maxWidth: 8000
        - maxHeight: 8000
file_constraints:
        - maxSize: '20M'
        - extensions: ['pdf', 'csv', 'txt', 'docx', 'mp3']
```

When using the validator version:

`symfony/validator  v4.1.6 `

I have this error:

Error: No default option is configured for constraint Symfony\Component\Validator\Constraints\File

It's fixed if I use this format:

```
    image_constraints: {minWidth: 100, minHeight: 100, maxWidth: 8000, maxHeight: 8000}
    file_constraints: {maxSize: '20M', extensions: ['pdf', 'csv', 'txt', 'docx', 'mp3']}
```
